### ISSUE TITLE
Conversion of non-promises to promises is problematic for AVA

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/observable-to-promise#2]
#1 Causes every argument to be converted to a via `Promise.resolve()`. That creates a small problem for AVA, since [this line](https://github.com/sindresorhus/ava/blob/dcf84b6f867d7b7aece83e59dcf99cbbc05a7bdc/lib/assert.js#L72) expects `isPromise(fn)` to be false if a `function` was passed in.

Also, the current behavior creates ambiguity, as:

``` js
observableToPromise([1,2]);
```

Produces an identical result to:

``` js
observableToPromise(Observable.of(1,2));
```

**Comment by sindresorhus** [comment]
I thought it was a good idea when I merged #1, but I noticed the issue with AVA too a while ago.

Do you have any suggested solution other than reverting?

// @mastilver

**Comment by mastilver** [comment]
the Promise.resolve is just there if you pass something which is not an observable

We could just check if the arg is not an `observable`, neither a `function`

If you are happy with that, I will create a PR in 5-6 hours

**Comment by mastilver** [comment]
Or we could only support `observable` and return the passed arg (as it was before my changes)

then you won't be able to do:

```
observable-to-promise(2).then(x => {
   console.log(x);
   // => 2
});
```

will throw `Uncaught TypeError: then is not a function`

**Comment by jamestalmage** [comment]
My only other thought was to throw a TypeError, if they pass a non observable.

It would require AVA do an `is-observable` test (so things would be a bit more verbose within AVA). However, I think it's a good change because then this API much more clear.

**Comment by mastilver** [comment]
> throw a TypeError

I'm happy with that

**Comment by sindresorhus** [comment]
> throw a TypeError

:+1:
